# Generated by Django 5.2.1 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_tournament_is_public_tournament_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='is_from_public',
            field=models.BooleanField(default=False),
        ),
    ]
