# Generated by Django 5.2.1 on 2025-07-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_is_from_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('anime', 'Anime/Manga'), ('nature', 'Nature'), ('architecture', 'Architecture'), ('people', 'People'), ('animals', 'Animals'), ('food', 'Food'), ('art', 'Art'), ('technology', 'Technology'), ('sports', 'Sports'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
